FROM node:lts-buster-slim

ARG YAPI_VERSION=1.10.2
ARG BUILD_PACKAGES="wget make python build-essential"

RUN apt-get update && apt-get install -y $BUILD_PACKAGES  \
    && mkdir /yapi && cd /yapi  \
    && wget https://github.com/YMFE/yapi/archive/refs/tags/v$YAPI_VERSION.tar.gz \
    && tar -zxf *.gz \
    && rm -f *.gz \
    && apt-get remove --purge -y $BUILD_PACKAGES && rm -rf /var/lib/apt/lists/* \
    && cd /yapi/yapi-$YAPI_VERSION \
    && npm install --production

#RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
#RUN apt-get update && apt-get install -y $BUILD_PACKAGES
#RUN mkdir /yapi
#COPY v$YAPI_VERSION.tar.gz /yapi/v$YAPI_VERSION.tar.gz
#RUN cd /yapi && tar -zxf *.gz
#COPY config.json /yapi/config.json
##RUN cd /yapi/yapi-$YAPI_VERSION && npm install --production --registry #https://registry.npm.taobao.org
#RUN apt-get remove --purge -y $BUILD_PACKAGES && rm -rf /var/lib/apt/lists/*

WORKDIR /yapi/yapi-$YAPI_VERSION

EXPOSE 3000
COPY config.json /yapi/config.json

CMD npm run start
